"use client";
import { useState } from "react";
import { API_BASE } from "../lib/api";

export default function LlmManagement({ llm, reload }: { llm: any; reload: () => Promise<void> }) {
  const [tab, setTab] = useState<"providers"|"models"|"skills">("providers");
  const [message, setMessage] = useState("");
  const request = async (url: string, options: RequestInit, ok: string) => { const r=await fetch(url,options); const b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.detail||b.error||"İşlem başarısız"); await reload(); setMessage(ok); window.alert(`${ok}.`); };
  const remove = async (url: string, label: string) => { if(!window.confirm(`${label} silinsin mi?`)) return; try { await request(url,{method:"DELETE"},`${label} silindi`); } catch(e) { setMessage(e instanceof Error?e.message:"Silinemedi"); } };
  const edit = async (kind:string, item:any) => { const name=window.prompt(`${kind} adı`,item.name); if(!name) return; const instructions=kind==="Uzmanlık"?window.prompt("Talimatlar",item.instructions):undefined; const baseUrl=kind==="Provider"?window.prompt("Base URL",item.base_url):undefined; try { await request(`${API_BASE}/api/llm/${kind==="Provider"?"providers":kind==="Model"?"models":"skills"}/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,...(instructions!==undefined?{instructions}:{}),...(baseUrl!==undefined?{base_url:baseUrl}:{}),temperature:item.temperature||0.2})},`${kind} güncellendi`); } catch(e){setMessage(e instanceof Error?e.message:"Güncellenemedi");} };
  return <div className="card bg-bunker-950 space-y-4"><div className="flex gap-2 border-b border-bunker-800 pb-2">{([["providers","Provider"],["models","Model"],["skills","Uzmanlık"]] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-3 py-2 rounded border font-mono text-xs ${tab===k?"border-neon-green/50 text-neon-green":"border-bunker-700 text-bunker-muted"}`}>{l}</button>)}</div>{message&&<p className="text-xs text-neon-green">{message}</p>}{tab==="providers"&&<div className="space-y-2">{llm.providers.map((p:any)=><div key={p.id} className="flex items-center justify-between gap-3 border-b border-bunker-800 py-2"><div><p className="font-mono text-sm text-white">{p.name}</p><p className="text-xs text-bunker-muted">{p.base_url}</p></div><div className="flex gap-3"><button onClick={()=>edit("Provider",p)} className="text-xs text-sky-300">DÜZENLE</button><button onClick={()=>remove(`${API_BASE}/api/llm/providers/${p.id}`,"Provider")} className="text-xs text-neon-red">SİL</button></div></div>)}</div>}{tab==="models"&&<div className="space-y-2">{llm.models.map((m:any)=><div key={m.id} className="flex items-center justify-between gap-3 border-b border-bunker-800 py-2"><div><p className="font-mono text-sm text-white">{m.name}</p><p className="text-xs text-bunker-muted">Provider ID: {m.provider_id}</p></div><div className="flex gap-3"><button onClick={()=>edit("Model",m)} className="text-xs text-sky-300">DÜZENLE</button><button onClick={()=>remove(`${API_BASE}/api/llm/models/${m.id}`,"Model")} className="text-xs text-neon-red">SİL</button></div></div>)}</div>}{tab==="skills"&&<div className="space-y-2">{llm.skills.map((s:any)=><div key={s.id} className="flex items-center justify-between gap-3 border-b border-bunker-800 py-2"><div><p className="font-mono text-sm text-white">{s.name}</p><p className="text-xs text-bunker-muted line-clamp-2">{s.instructions}</p></div><div className="flex gap-3"><button onClick={()=>edit("Uzmanlık",s)} className="text-xs text-sky-300">DÜZENLE</button><button onClick={()=>remove(`${API_BASE}/api/llm/skills/${s.id}`,"Uzmanlık")} className="text-xs text-neon-red">SİL</button></div></div>)}</div>}</div>;
}
