"use client";
import { useEffect, useMemo, useState } from "react";
import { API_BASE } from "../lib/api";

type Trade = { id: number; symbol: string; strategy: string; pnl: number; pnl_pct: number; reason?: string; entry_time: number; exit_time: number; commission?: number };
type Signal = { symbol: string; action: string; reason?: string; timestamp?: number };

const label = (s: string) => ({ MOMENTUM: "MTF Momentum Ranking", EMA_VWAP_PULLBACK: "EMA + VWAP Pullback", VWAP_MEAN_REVERSION: "VWAP Mean Reversion", CHOP_TREND_FILTER: "CHOP Trend Filter", KELTNER_BREAKOUT: "Keltner Breakout", DONCHIAN_BREAKOUT: "Donchian Breakout", GAINER_RADAR: "Gainer Radar" }[s] || s || "Bilinmiyor");
const money = (v: number) => `₺${v.toLocaleString("tr-TR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const time = (v?: number) => v ? new Date(v * 1000).toLocaleString("tr-TR", { hour12: false }) : "—";

export default function ReportsPage() {
  const [trades, setTrades] = useState<Trade[]>([]); const [signals, setSignals] = useState<Signal[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([fetch(`${API_BASE}/api/trades`).then(r => r.json()), fetch(`${API_BASE}/api/signals?limit=500`).then(r => r.json())]).then(([t, s]) => { setTrades(t.trades || []); setSignals(s.signals || []); }).catch(() => setError("Rapor verileri alınamadı")); }, []);
  const grouped = (key: "symbol" | "strategy" | "reason") => Object.entries(trades.reduce<Record<string, { n: number; pnl: number; wins: number }>>((a, t) => { const k = String(t[key] || "Bilinmiyor"); const x = a[k] || { n: 0, pnl: 0, wins: 0 }; x.n++; x.pnl += t.pnl || 0; if (t.pnl > 0) x.wins++; a[k] = x; return a; }, {})).sort((a, b) => a[1].pnl - b[1].pnl);
  const timeout = trades.filter(t => t.reason === "max_hold_2h"); const missing = useMemo(() => ({ liquidity: trades.length, scores: trades.length }), [trades.length]);
  return <div className="max-w-7xl mx-auto space-y-6"><header><h1 className="font-mono text-xl font-bold"><span className="text-neon-green">RAPORLAR</span></h1><p className="eyebrow mt-1">İşlem kalitesi · timeout · sembol ve strateji analizi</p></header>{error && <div className="card border-neon-red/40 text-neon-red font-mono text-sm">{error}</div>}
    <div className="grid md:grid-cols-4 gap-4"><div className="card"><p className="eyebrow">İŞLEM</p><p className="font-mono text-2xl text-white mt-1">{trades.length}</p></div><div className="card"><p className="eyebrow">TOPLAM PnL</p><p className={`font-mono text-2xl mt-1 ${trades.reduce((a,t)=>a+t.pnl,0)>=0?"text-neon-green":"text-neon-red"}`}>{money(trades.reduce((a,t)=>a+t.pnl,0))}</p></div><div className="card"><p className="eyebrow">2 SAAT TIMEOUT</p><p className="font-mono text-2xl text-neon-red mt-1">{timeout.length}</p></div><div className="card"><p className="eyebrow">SİNYAL KAYDI</p><p className="font-mono text-2xl text-white mt-1">{signals.length}</p></div></div>
    <div className="card border-yellow-500/30 bg-yellow-500/5"><p className="eyebrow text-yellow-300">VERİ KAPSAMI</p><p className="text-sm text-white mt-2">Mevcut trade şemasında giriş spread’i, order-book derinliği, hacim oranı ve sinyal skoru tutulmuyor. Bu alanlar “bilinmiyor” olarak bırakılır; geçmişe dönük tahmin edilmez.</p><p className="text-xs text-bunker-muted mt-2">Likidite metadata kaydı: {missing.liquidity ? "eksik" : "işlem yok"} · Sinyal skorları: eksik</p></div>
    {[["Kapanış nedeni", "reason"], ["Strateji", "strategy"], ["Sembol", "symbol"]].map(([title,key]) => <section className="card bg-bunker-950" key={key}><p className="eyebrow">{title.toUpperCase()} BAZINDA RAPOR</p><div className="overflow-x-auto mt-3"><table className="w-full text-left font-mono text-xs"><thead className="text-bunker-muted"><tr><th className="p-2">Grup</th><th className="p-2">İşlem</th><th className="p-2">Başarı</th><th className="p-2">PnL</th></tr></thead><tbody>{grouped(key as any).map(([k,x]) => <tr className="border-t border-bunker-800/60" key={k}><td className="p-2 text-white">{key === "strategy" ? label(k) : k}</td><td className="p-2">{x.n}</td><td className="p-2">%{(x.wins / x.n * 100).toFixed(1)}</td><td className={`p-2 ${x.pnl >= 0 ? "text-neon-green" : "text-neon-red"}`}>{money(x.pnl)}</td></tr>)}</tbody></table></div></section>)}
    <section className="card bg-bunker-950"><p className="eyebrow">SON TIMEOUT İŞLEMLERİ</p><div className="overflow-x-auto mt-3"><table className="w-full text-left font-mono text-xs"><thead className="text-bunker-muted"><tr><th className="p-2">Sembol</th><th className="p-2">Strateji</th><th className="p-2">Açılış</th><th className="p-2">PnL</th></tr></thead><tbody>{timeout.slice(0,20).map(t => <tr className="border-t border-bunker-800/60" key={t.id}><td className="p-2 text-white">{t.symbol}</td><td className="p-2">{label(t.strategy)}</td><td className="p-2">{time(t.entry_time)}</td><td className="p-2 text-neon-red">{money(t.pnl)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
