"use client";
import { useState } from "react";
import { API_BASE } from "../lib/api";
import { streamChat } from "../lib/streamChat";
import MarkdownMessage from "../components/MarkdownMessage";

export default function StrategyLlm(){
 const [messages,setMessages]=useState<any[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false);
 const send=async()=>{const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user",content:text}];setMessages([...next,{role:"assistant",content:""}]);setInput("");setBusy(true);try{await streamChat(`${API_BASE}/api/strategies/llm/chat`,next,(delta)=>setMessages(current=>[...current.slice(0,-1),{role:"assistant",content:(current[current.length-1]?.content||"")+delta}]))}catch(error){setMessages(current=>[...current.slice(0,-1),{role:"assistant",content:error instanceof Error?error.message:"LLM bağlantısı kurulamadı."}])}finally{setBusy(false)}};
 return <div className="strategy-llm grid lg:grid-cols-2 gap-6 items-start"><div className="card bg-bunker-950"><p className="eyebrow">STRATEJİ VE GEÇMİŞ VERİLERİYLE SOHBET</p><p className="text-xs text-bunker-muted mt-2">Aktif ayarlar, işlem geçmişi, sinyaller ve strateji istatistikleri her soruda güncellenerek kullanılır.</p><div className="strategy-llm-messages h-[30rem] overflow-y-auto space-y-3 mt-4">{!messages.length&&<p className="text-sm text-bunker-muted">Örn: “Hangi strateji komisyon sonrası en iyi performansı verdi?”</p>}{messages.map((m,i)=><div key={i} className={`p-3 rounded-lg text-sm ${m.role==="user"?"bg-neon-green/10 ml-6":"bg-bunker-800 mr-6"}`}><p className="eyebrow mb-1">{m.role==="user"?"SİZ":"LLM"}</p><MarkdownMessage content={m.content}/></div>)}{busy&&<p className="text-xs text-yellow-300">İşlem ve sinyal geçmişi sorgulanıyor...</p>}</div><div className="flex gap-2 mt-4"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Stratejiler veya geçmiş hakkında soru sor" className="input flex-1 min-w-0"/><button onClick={send} disabled={busy||!input.trim()} className="min-h-11 px-4 rounded-lg border border-neon-green/50 text-neon-green disabled:opacity-50">GÖNDER</button></div></div><div className="card bg-bunker950"><p className="eyebrow">LLM’İN ERİŞEBİLDİĞİ KAPSAM</p><div className="mt-4 space-y-2 text-sm text-bunker-muted">{["Mevcut strateji ayarları ve timeframe’ler","Tüm strateji performans istatistikleri","Kapanmış işlem geçmişi ve net PnL","Komisyon sonrası başarı oranları","Sinyal geçmişi ve kapanış nedenleri","Paper trading risk kuralları"].map(x=><p key={x}>✓ {x}</p>)}</div><p className="text-xs text-bunker-muted mt-5">Yanıtlar Türkçe üretilir; LLM işlem açamaz, kapatamaz veya risk kurallarını değiştiremez.</p></div></div>;
}
