"use client";
import { useEffect, useState } from "react";
import { API_BASE } from "../lib/api";

export default function MigrationMonitor() {
  const [state, setState] = useState<any>(null); const [source, setSource] = useState(""); const [starting, setStarting] = useState(false); const [message, setMessage] = useState("");
  const load = async () => { try { setState(await (await fetch(`${API_BASE}/api/migration/status`, { cache:"no-store" })).json()); } catch { setMessage("Migration status alınamadı"); } };
  useEffect(() => { load(); const id = window.setInterval(load, 1000); return () => window.clearInterval(id); }, []);
  const start = async () => { if (!window.confirm("Migration başlatılacak. SQLite verisi silinmeyecek, ancak işlem sırasında yeni işlem açılışı geçici olarak durdurulacak. Devam edilsin mi?")) return; setStarting(true); setMessage(""); try { const r=await fetch(`${API_BASE}/api/migration/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(source ? {source}: {})}); const b=await r.json(); if(!r.ok) throw new Error(b.detail||"Başlatılamadı"); setMessage("Migration başlatıldı"); setState(b); } catch(e) { setMessage(e instanceof Error?e.message:"Migration başlatılamadı"); } finally { setStarting(false); } };
  const counts = state?.source?.counts || {};
  return <main className="page-shell"><div className="page-heading"><p className="eyebrow">GEÇİCİ YÖNETİM ARAYÜZÜ</p><h1>Migration Monitor</h1><p className="text-bunker-muted">SQLite → PostgreSQL + pgvector geçişini izleyin.</p></div><div className="panel p-5"><label className="eyebrow">SQLite kaynak yolu</label><input value={source} onChange={e=>setSource(e.target.value)} placeholder="Boş bırakılırsa sunucu DB kaynağı kullanılır" className="input w-full mt-2"/><div className="mt-5 flex items-center gap-4"><div className="h-3 flex-1 rounded bg-bunker-800 overflow-hidden"><div className="h-full bg-neon-green transition-all" style={{width:`${state?.progress||0}%`}} /></div><span className="font-mono text-sm">{state?.progress||0}%</span></div><p className="font-mono text-sm mt-3">{state?.message || "Hazır"} · {state?.phase || "idle"}</p>{state?.error && <p className="text-red-400 mt-2">{state.error}</p>}<button onClick={start} disabled={starting || state?.status === "running" || state?.status === "completed"} className="mt-5 px-4 py-2 rounded border border-neon-green/50 text-neon-green font-mono text-xs disabled:opacity-40">{starting || state?.status === "running" ? "MIGRATION ÇALIŞIYOR…" : "MİGRASYONU BAŞLAT"}</button>{message&&<p className="text-neon-green text-sm mt-3">{message}</p>}</div><div className="panel p-5 mt-5"><h2 className="font-mono">Kaynak kayıt sayıları</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">{Object.entries(counts).map(([k,v])=><div className="border border-bunker-700 rounded p-3" key={k}><p className="eyebrow">{k}</p><p className="font-mono text-lg mt-1">{String(v)}</p></div>)}</div><p className="text-xs text-bunker-muted mt-4 break-all">SHA-256: {state?.source?.sha256 || "—"}</p></div></main>;
}
