"use client";
import { useEffect, useState } from "react";
import { apiFetch } from "../lib/api";

export default function MemoryPage() {
  const [status, setStatus] = useState<any>(null); const [query, setQuery] = useState(""); const [results, setResults] = useState<any[]>([]); const [error, setError] = useState("");
  useEffect(() => { apiFetch("/api/memory/status").then(setStatus).catch(() => setError("Memory durumu alınamadı")); }, []);
  const search = async () => { setError(""); try { const body = await apiFetch("/api/memory/retrieve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query, limit: 8 }) }); setResults(body.results || []); } catch (e) { setError(e instanceof Error ? e.message : "Retrieval başarısız"); } };
  return <main className="page-shell"><div className="page-heading"><p className="eyebrow">LLM HAFIZASI</p><h1>Embedding ve Retrieval</h1><p className="text-bunker-muted">Geçmiş işlem ve karar bağlamını yalnızca PostgreSQL memory backend aktifken arar.</p></div><div className="grid md:grid-cols-4 gap-3">{[["Durum", status?.enabled ? "Aktif" : "Pasif"],["Kuyruk", status?.worker?.pending ?? "—"],["İşlenen", status?.worker?.processed ?? "—"],["Hata", status?.worker?.failed ?? "—"]].map(([a,b]) => <div className="panel p-4" key={a}><p className="eyebrow">{a}</p><p className="text-xl font-mono mt-2">{b}</p></div>)}</div><div className="panel p-5 mt-5"><div className="flex gap-2"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Örn. BTCTRY benzer timeout işlemleri" className="input flex-1" /><button onClick={search} disabled={!query.trim()} className="px-4 py-2 rounded border border-neon-green/40 text-neon-green font-mono text-xs">ARA</button></div>{error && <p className="text-red-400 text-sm mt-3">{error}</p>}<div className="mt-5 space-y-3">{results.map(r => <article className="border border-bunker-700 rounded p-3" key={r.id}><div className="flex justify-between text-xs font-mono text-bunker-muted"><span>{r.symbol || "global"} · {r.layer}</span><span>{Number(r.similarity || 0).toFixed(3)}</span></div><p className="text-sm mt-2 whitespace-pre-wrap">{r.content}</p></article>)}</div></div></main>;
}
