"use client";
import { useEffect, useMemo, useState } from "react";
import { API_BASE } from "../lib/api";

const pct = (v: any) => v == null ? "—" : `${(v * 100).toFixed(2)}%`;
const num = (v: any, d = 4) => v == null ? "—" : Number(v).toLocaleString("tr-TR", { maximumFractionDigits: d });
const Card = ({ title, children }: any) => <div className="card bg-bunker-950 border border-bunker-800"><p className="eyebrow">{title}</p><div className="mt-3">{children}</div></div>;

export default function SymbolAnalysisPage() {
  const [symbol, setSymbol] = useState("BTCTRY"); const [symbols, setSymbols] = useState<string[]>([]); const [data, setData] = useState<any>(null); const [llm, setLlm] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("symbol"); fetch(`${API_BASE}/api/config`).then(r => r.json()).then(d => { const list = d.symbols || []; setSymbols(list); setSymbol(requested || list[0] || "BTCTRY"); }).catch(() => setError("Semboller alınamadı")); }, []);
  useEffect(() => { if (!symbol) return; const load = () => fetch(`${API_BASE}/api/symbol-analysis/${symbol}`).then(r => r.json()).then(setData).catch(() => setError("Teknik veri alınamadı")); load(); const id = setInterval(load, 5000); return () => clearInterval(id); }, [symbol]);
  useEffect(() => { setLlm(null); if (!symbol || !data?.data_ready) return; fetch(`${API_BASE}/api/symbol-analysis/${symbol}/llm`, { method: "POST" }).then(r => r.json()).then(setLlm).catch(() => setLlm({ status: "unavailable" })); }, [symbol, data?.data_ready]);
  const t = data?.trend || {}, m = data?.momentum || {}, v = data?.volatility || {}, vol = data?.volume || {}, l = data?.liquidity || {};
  const fields = useMemo(() => [["EMA 9", num(t.ema_9)], ["EMA 21", num(t.ema_21)], ["EMA 50", num(t.ema_50)], ["ADX", num(t.adx?.adx, 2)], ["RSI 14", num(m.rsi_14, 2)], ["MFI 14", num(m.mfi_14, 2)], ["MACD hist", num(m.macd?.histogram, 4)], ["Stoch %K", num(m.stochastic?.k, 2)], ["ATR %", pct(v.atr_pct)], ["ADR 14", pct(v.adr_14_pct)], ["BB genişliği", pct(v.bollinger?.width_pct)], ["Hacim oranı", vol.volume_ratio_20 == null ? "—" : `${num(vol.volume_ratio_20, 2)}x`], ["OBV eğimi", num(vol.obv?.slope, 2)], ["Spread", pct(l.spread_pct == null ? null : l.spread_pct / 100)], ["Depth çarpanı", l.depth_multiplier == null ? "—" : `${num(l.depth_multiplier, 2)}x`]], [t,m,v,vol,l]);
  return <div className="max-w-7xl mx-auto space-y-6"><header className="flex flex-col md:flex-row md:items-end md:justify-between gap-4"><div><h1 className="font-mono text-xl font-bold"><span className="text-neon-green">SEMBOL</span> ANALİZİ</h1><p className="eyebrow mt-1">Canlı teknik bağlam · public market data</p></div><div className="flex gap-2"><input value={symbol} onChange={e => setSymbol(e.target.value.toUpperCase())} list="symbol-list" className="w-36 bg-bunker-900 border border-bunker-700 rounded-lg px-3 py-2 font-mono text-sm text-white" placeholder="Sembol" /><datalist id="symbol-list">{symbols.map(s => <option key={s} value={s} />)}</datalist><select value={symbol} onChange={e => setSymbol(e.target.value)} className="bg-bunker-900 border border-bunker-700 rounded-lg px-3 py-2 font-mono text-sm text-white"><option value="">Seç...</option>{symbols.map(s => <option key={s}>{s}</option>)}</select></div></header>{error && <div className="card text-neon-red font-mono text-sm">{error}</div>}{!data?.data_ready ? <div className="card text-bunker-muted font-mono text-sm">Veri ısınıyor veya sembol bulunamadı...</div> : <><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Card title="ANLIK FİYAT"><p className="font-mono text-2xl text-white">₺{num(data.price)}</p></Card><Card title="TREND"><p className="font-mono text-xl text-neon-green">{t.alignment?.toUpperCase()}</p></Card><Card title="ÖZET"><p className="font-mono text-xl text-white">{data.summary?.toUpperCase()}</p></Card><Card title="ADR KAPASİTESİ"><p className="font-mono text-xl text-neon-yellow">{pct(v.remaining_capacity_pct)}</p></Card></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4"><Card title="TEKNİK GÖSTERGELER"><div className="grid grid-cols-2 gap-3">{fields.map(([a,b]) => <div key={a}><p className="text-xs text-bunker-muted">{a}</p><p className="font-mono text-white">{b}</p></div>)}</div></Card><Card title="MOMENTUM / VOLATİLİTE"><div className="grid grid-cols-2 gap-3">{[["5dk",pct(m.return_5m)],["15dk",pct(m.return_15m)],["1s",pct(m.return_1h)],["ROC 21",pct(m.roc_21)],["ADR kullanım",pct(v.adr_utilization)],["VWAP",num(vol.vwap)]].map(([a,b]) => <div key={a}><p className="text-xs text-bunker-muted">{a}</p><p className="font-mono text-white">{b}</p></div>)}</div></Card><Card title="LLM TEKNİK YORUM"><p className="text-xs text-bunker-muted mb-2">Salt-okuma yorumlama · emir üretmez.</p>{!llm && <p className="font-mono text-sm text-bunker-muted">LLM pasif veya analiz hazırlanıyor...</p>}{llm?.status === "ok" && <p className="text-sm text-white whitespace-pre-wrap">{llm.text}</p>}{llm?.status === "error" && <p className="text-sm text-neon-red">LLM hatası: {llm.error}</p>}</Card></div><Card title="VERİ KAYNAĞI"><p className="text-sm text-white">Binance TR public OHLCV, order-flow ve ticker verisi.</p><p className="text-xs text-bunker-muted mt-2">Likidite alanları veri yoksa tahmin edilmez.</p></Card></>}</div>;
}
